name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get install -y binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
        sudo apt-get install -y wine
    - name: Build
      run: |
        # make sure units are compiled separately
        x86_64-w64-mingw32-g++ -O3 -c main.cpp
        x86_64-w64-mingw32-g++ -O3 -c func.cpp
        x86_64-w64-mingw32-g++ -O3 -c func2.cpp
        x86_64-w64-mingw32-g++ -static -static-libgcc -static-libstdc++ main.o func.o func2.o -o run.exe
        g++ -O3 -c main.cpp
        g++ -O3 -c func.cpp
        g++ -O3 -c func2.cpp
        g++  main.o func.o func2.o -o run
    - name: Run
      run: |
        wine $PWD/run.exe
        ./run
