name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install generic packages
      run: |
        sudo apt-get install -y binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64
    - name: Build
      run: |
        x86_64-w64-mingw32-gcc -O3 -static -static-libgcc main.c func.c -o run.exe
        gcc -O3 main.c func.c -o run
    - name: Run
      run: |
        sudo apt-get install -y wine
        wine $PWD/run.exe
        ./run
